name: Release the competition boundle

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - uses: actions/upload-artifact@v4
      with:
        name: code_submission_bundle
        path: code_submission_bundle

    - uses: actions/upload-artifact@v4
      with:
        name: sample_code_submission
        path: sample_code_submission

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: code_submission_bundle
        asset_name: code_submission_bundle
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is the submission bundle for creating the competition"

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sample_code_submission
        asset_name: sample_code_submission
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is an example for code submission"
        
